[extensions.avro]
package = "morphir-avro-extension"
artifact = "morphir-avro-extension"
extension_id = "morphir-avro"
name = "Morphir Avro"
mep_versions = ["0.1"]
targets = ["avro"]
ir_versions = ["3", "4"]
release_with_workspace = true

[extensions.openapi]
package = "morphir-openapi-extension"
artifact = "morphir-openapi-extension"
extension_id = "morphir-openapi"
name = "Morphir OpenAPI"
mep_versions = ["0.1"]
targets = ["openapi", "json-schema"]
ir_versions = ["3", "4"]
release_with_workspace = true
