//! Integration tests for loading Classic IR JSON files
//!
//! These tests verify that the Classic IR structures can successfully load
//! actual morphir-ir.json files generated by morphir-elm.

use morphir_core::ir::classic::Distribution;
use std::fs;

/// Path to reference-model morphir-ir.json (absolute path for CI consistency)
const REFERENCE_MODEL_IR: &str = "/home/damian/code/repos/github/finos/morphir-elm/tests-integration/reference-model/morphir-ir.json";

/// Path to LCR morphir-ir.json if available
const LCR_MODEL_IR: &str = "/home/damian/code/repos/github/finos/morphir-elm/morphir-ir.json";

#[test]
fn test_load_reference_model_distribution() {
    // Skip if the file doesn't exist (e.g., morphir-elm not checked out)
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(REFERENCE_MODEL_IR);
    if !path.exists() {
        eprintln!(
            "Skipping test: reference model not found at {:?}",
            path
        );
        return;
    }

    let content = fs::read_to_string(&path).expect("Failed to read morphir-ir.json");
    
    // Try to parse via Value to bypass recursion limit issues in from_str
    let json_val: serde_json::Value = serde_json::from_str(&content).expect("Failed to parse to Value");
    let result: Result<Distribution, _> = serde_json::from_value(json_val);
    
    match result {
        Ok(dist) => {
            println!("Successfully loaded distribution!");
            println!("  Format version: {}", dist.format_version);
            // Print some basic info about the distribution
            match &dist.distribution {
                morphir_core::ir::classic::DistributionBody::Library(package_name, _deps, package) => {
                    println!("  Package name: {:?}", package_name);
                    println!("  Module count: {}", package.modules.len());
                }
            }
        }
        Err(e) => {
            // Print helpful debug info
            eprintln!("Failed to parse distribution: {}", e);
            
            // Try to find what line/column the error is at
            if let Some(line) = content.lines().nth(0) {
                eprintln!("First line: {}", &line[..line.len().min(200)]);
            }
            
            panic!("Failed to parse distribution: {}", e);
        }
    }
}

#[test]
fn test_load_lcr_model_distribution() {
    // Skip if the file doesn't exist
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(LCR_MODEL_IR);
    if !path.exists() {
        eprintln!(
            "Skipping test: LCR model not found at {:?}",
            path
        );
        return;
    }

    let content = fs::read_to_string(&path).expect("Failed to read LCR morphir-ir.json");
    
    // Try to parse via Value to bypass recursion limit issues in from_str
    let json_val: serde_json::Value = serde_json::from_str(&content).expect("Failed to parse to Value");
    let result: Result<Distribution, _> = serde_json::from_value(json_val);
    
    match result {
        Ok(dist) => {
            println!("Successfully loaded LCR distribution!");
            println!("  Format version: {}", dist.format_version);
            match &dist.distribution {
                morphir_core::ir::classic::DistributionBody::Library(package_name, _, package) => {
                    println!("  Package name: {:?}", package_name);
                    println!("  Module count: {}", package.modules.len());
                    
                    // Print some module info
                    for (i, entry) in package.modules.iter().take(5).enumerate() {
                        println!("  Module {}: {:?}", i, entry.path);
                    }
                }
            }
        }
        Err(e) => {
            panic!("Failed to parse LCR distribution: {}", e);
        }
    }
}
