#!/bin/sh
#MISE description="Serve Jekyll documentation site locally"
#MISE depends=["docs:setup"]

set -e

cd docs

echo "Starting Jekyll server..."
echo "Note: Sass deprecation warnings are from the just-the-docs theme and can be ignored."
echo ""

bundle exec jekyll serve --livereload --baseurl ""
