[package]
name = "morphir-python-binding"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Python ADT, tuple, function and lambda frontend and backend for Morphir"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
num-bigint.workspace = true
morphir-core = { path = "../morphir-core", version = "0.2.0" }
morphir-extension-sdk = { path = "../morphir-extension-sdk", version = "0.2.0" }
ruff_python_parser.workspace = true
ruff_python_ast.workspace = true
ruff_python_codegen.workspace = true
ruff_text_size.workspace = true
serde_json = "1.0"

[dev-dependencies]
tempfile.workspace = true
cucumber = "0.23"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[test]]
name = "acceptance"
harness = false
