//! Backend visitor - converts Morphir IR V4 to Gleam source code
//!
//! This visitor traverses Morphir IR structures and generates Gleam source code,
//! using Vfs for file generation.

use super::names::{ModuleNames, module_path};
use crate::vfs::Vfs;
use morphir_core::ir::Value;
use morphir_core::ir::v4::{
    Access as MorphirAccess, AccessControlled, Documented, Literal as MorphirLiteral,
    ModuleDefinition, Pattern as MorphirPattern, TypeDefinition, ValueDefinition,
};
use morphir_core::naming::{ModuleName, Name, Path};
use std::cell::RefCell;
use std::io::Result;
use std::path::PathBuf;

// Type alias for the new V4 generic AccessControlled type
type AccessControlledModuleDefinition = AccessControlled<ModuleDefinition>;
type AccessControlledTypeDefinition = AccessControlled<Documented<TypeDefinition>>;
type AccessControlledValueDefinition = AccessControlled<Documented<ValueDefinition>>;

/// Visitor that converts Morphir IR V4 to Gleam source code
pub struct MorphirToGleamVisitor<V: Vfs> {
    vfs: V,
    output_dir: PathBuf,
    package_name: String,
    names: RefCell<ModuleNames>,
}

impl<V: Vfs> MorphirToGleamVisitor<V> {
    /// Create a new visitor
    pub fn new(vfs: V, output_dir: PathBuf, package_name: String) -> Self {
        Self {
            vfs,
            output_dir,
            package_name,
            names: RefCell::new(ModuleNames::default()),
        }
    }

    /// Convert ModuleDefinition to Gleam source file
    pub fn visit_module(
        &self,
        module_name: &ModuleName,
        module: &AccessControlledModuleDefinition,
    ) -> Result<()> {
        // Convert module path to file path: "my/module" -> "my/module.gleam"
        let file_path = self
            .output_dir
            .join(format!("{}.gleam", module_path(module_name.as_path())));

        // Generate module content
        let content = self.generate_module_content(module_name, &module.value)?;

        // Write to Vfs
        self.vfs.write_from_string(&file_path, &content)?;
        Ok(())
    }

    /// Generate module content as string
    fn generate_module_content(
        &self,
        module_name: &ModuleName,
        module: &ModuleDefinition,
    ) -> Result<String> {
        *self.names.borrow_mut() = ModuleNames::default();
        self.names.borrow_mut().module = Some(module_name.clone());
        let mut output = String::new();

        if let Some(doc) = &module.doc {
            for line in doc.lines() {
                output.push_str(&format!("//// {line}\n"));
            }
        }

        // Module header comment
        output.push_str("// Generated by Morphir Gleam Backend\n");
        output.push('\n');

        // Generate type definitions
        for (type_name, type_def) in &module.types {
            self.generate_type_def(&mut output, type_name, type_def)?;
            output.push('\n');
        }

        // Generate value definitions
        for (value_name, value_def) in &module.values {
            self.generate_value_def(&mut output, value_name, value_def)?;
            output.push('\n');
        }

        let imports = self.names.borrow().declarations();
        if !imports.is_empty() {
            output.insert_str(
                output
                    .find("\n\n")
                    .map(|position| position + 2)
                    .unwrap_or(0),
                &format!("{imports}\n"),
            );
        }
        Ok(output)
    }

    /// Generate a type definition
    fn generate_type_def(
        &self,
        output: &mut String,
        type_name: &str,
        type_def: &AccessControlledTypeDefinition,
    ) -> Result<()> {
        if let Some(doc) = &type_def.value.doc {
            for line in doc.lines() {
                output.push_str(&format!("/// {line}\n"));
            }
        }
        if matches!(type_def.access, MorphirAccess::Public) {
            output.push_str("pub ");
        }
        if matches!(&type_def.value.value, TypeDefinition::CustomTypeDefinition { constructors, .. } if constructors.access == MorphirAccess::Private)
        {
            output.push_str("opaque ");
        }
        output.push_str("type ");
        let name = Name::from_canonical_string(type_name)
            .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidInput, error))?;
        output.push_str(&name.to_title_case());
        let params = match &type_def.value.value {
            TypeDefinition::TypeAliasDefinition { type_params, .. }
            | TypeDefinition::CustomTypeDefinition { type_params, .. } => type_params,
            TypeDefinition::IncompleteTypeDefinition { .. } => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    format!("Cannot generate incomplete type '{type_name}'"),
                ));
            }
        };
        if !params.is_empty() {
            output.push('(');
            output.push_str(
                &params
                    .iter()
                    .map(Name::to_snake_case)
                    .collect::<Vec<_>>()
                    .join(", "),
            );
            output.push(')');
        }
        match &type_def.value.value {
            TypeDefinition::TypeAliasDefinition {
                type_expr: morphir_core::ir::Type::Record(_, fields),
                ..
            } => {
                // Gleam represents named records with a single labelled constructor.
                // This gives a structural IR record a nominal Gleam name.
                output.push_str(" {\n  ");
                output.push_str(&name.to_title_case());
                if !fields.is_empty() {
                    output.push('(');
                    for (index, field) in fields.iter().enumerate() {
                        if index > 0 {
                            output.push_str(", ");
                        }
                        output.push_str(&field.name.to_snake_case());
                        output.push_str(": ");
                        self.generate_type_expr(output, &field.tpe)?;
                    }
                    output.push(')');
                }
                output.push_str("\n}\n");
            }
            TypeDefinition::TypeAliasDefinition { type_expr, .. } => {
                output.push_str(" = ");
                self.generate_type_expr(output, type_expr)?;
                output.push('\n');
            }
            TypeDefinition::CustomTypeDefinition { constructors, .. } => {
                output.push_str(" {\n");
                for constructor in &constructors.value {
                    output.push_str("  ");
                    output.push_str(&constructor.name.to_title_case());
                    if !constructor.args.is_empty() {
                        output.push('(');
                        for (index, arg) in constructor.args.iter().enumerate() {
                            if index > 0 {
                                output.push_str(", ");
                            }
                            let label = arg.name.to_snake_case();
                            // Gleam also permits positional calls to labelled arguments.
                            output.push_str(&label);
                            output.push_str(": ");
                            self.generate_type_expr(output, &arg.arg_type)?;
                        }
                        output.push(')');
                    }
                    output.push('\n');
                }
                output.push_str("}\n");
            }
            TypeDefinition::IncompleteTypeDefinition { .. } => unreachable!(),
        }
        Ok(())
    }

    /// Generate a Gleam type expression from IR Type
    fn generate_type_expr(
        &self,
        output: &mut String,
        type_expr: &morphir_core::ir::Type,
    ) -> Result<()> {
        use morphir_core::ir::Type;

        match type_expr {
            Type::Variable(_, name) => {
                output.push_str(&name.to_snake_case());
            }
            Type::Reference(_, fqname, args) => {
                let local = fqname.local_name.to_title_case();
                let sdk = fqname.package_path == Path::new("morphir/SDK");
                let sdk_type = if sdk {
                    match (module_path(&fqname.module_path).as_str(), local.as_str()) {
                        ("basics", "Int" | "Float" | "Bool")
                        | ("string", "String")
                        | ("list", "List")
                        | ("result", "Result") => Some(local.clone()),
                        ("maybe", "Maybe") => Some(format!(
                            "{}.Option",
                            self.names
                                .borrow_mut()
                                .import("gleam/option", &Path::new("gleam/stdlib"))?
                        )),
                        (module @ "dict", "Dict") | (module @ "set", "Set") => Some(format!(
                            "{}.{local}",
                            self.names
                                .borrow_mut()
                                .import(&format!("gleam/{module}"), &Path::new("gleam/stdlib"),)?
                        )),
                        _ => {
                            return Err(std::io::Error::new(
                                std::io::ErrorKind::InvalidInput,
                                format!("No Gleam mapping for SDK type '{fqname}'"),
                            ));
                        }
                    }
                } else {
                    None
                };
                output.push_str(&match sdk_type {
                    Some(mapped) => mapped,
                    None => self
                        .names
                        .borrow_mut()
                        .reference(&self.package_name, fqname, local)?,
                });
                if !args.is_empty() {
                    output.push('(');
                    for i in 0..args.len() {
                        if i > 0 {
                            output.push_str(", ");
                        }
                        let index = if sdk
                            && module_path(&fqname.module_path) == "result"
                            && args.len() == 2
                        {
                            1 - i
                        } else {
                            i
                        };
                        let arg = &args[index];
                        self.generate_type_expr(output, arg)?;
                    }
                    output.push(')');
                }
            }
            Type::Tuple(_, elements) => {
                output.push_str("#(");
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    self.generate_type_expr(output, elem)?;
                }
                output.push(')');
            }
            Type::Record(..) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "An anonymous nested structural record needs a named type alias for Gleam generation",
                ));
            }
            Type::ExtensibleRecord(..) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "Gleam cannot represent an extensible structural record with an open row",
                ));
            }
            Type::Function(_, arg_type, return_type) => {
                output.push_str("fn(");
                self.generate_type_expr(output, arg_type)?;
                output.push_str(") -> ");
                self.generate_type_expr(output, return_type)?;
            }
            Type::Unit(_) => {
                output.push_str("Nil");
            }
        }

        Ok(())
    }

    /// Generate a value definition
    fn generate_value_def(
        &self,
        output: &mut String,
        value_name: &str,
        value_def: &AccessControlledValueDefinition,
    ) -> Result<()> {
        if let Some(doc) = &value_def.value.doc {
            for line in doc.lines() {
                output.push_str(&format!("/// {line}\n"));
            }
        }
        // Access control
        if matches!(value_def.access, MorphirAccess::Public) {
            output.push_str("pub ");
        }

        output.push_str("fn ");
        output.push_str(
            &Name::from_canonical_string(value_name)
                .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidInput, error))?
                .to_snake_case(),
        );
        output.push('(');

        // Parameters
        for (i, input) in value_def.value.value.input_types.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            output.push_str(
                &Name::from_canonical_string(input.0)
                    .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidInput, error))?
                    .to_snake_case(),
            );
        }

        output.push_str(") {\n  ");

        // Body - V4 now stores body as actual Value
        match &value_def.value.value.body {
            morphir_core::ir::v4::ValueBody::Expression(body) => {
                self.generate_value_expr(output, body)?;
            }
            morphir_core::ir::v4::ValueBody::Native { .. } => {
                return Err(unsupported("Native definition body"));
            }
            morphir_core::ir::v4::ValueBody::External { .. } => {
                return Err(unsupported("External definition body"));
            }
            morphir_core::ir::v4::ValueBody::Incomplete { .. } => {
                return Err(unsupported("Incomplete definition body"));
            }
        }

        output.push_str("\n}\n");
        Ok(())
    }

    /// Generate value expression
    fn generate_value_expr(&self, output: &mut String, value: &Value) -> Result<()> {
        match value {
            Value::Literal(_, lit) => {
                self.generate_literal(output, lit)?;
            }
            Value::Variable(_, name) => {
                output.push_str(&name.to_snake_case());
            }
            Value::Apply(_, function, argument) => {
                if let Value::Apply(_, cons, head) = function.as_ref()
                    && let Value::Reference(_, name) = cons.as_ref()
                    && name.package_path == Path::new("morphir/SDK")
                    && name.module_path == Path::new("list")
                    && name.local_name == Name::from("cons")
                {
                    output.push('[');
                    self.generate_value_expr(output, head)?;
                    output.push_str(", ..");
                    self.generate_value_expr(output, argument)?;
                    output.push(']');
                    return Ok(());
                }
                self.generate_value_expr(output, function)?;
                output.push('(');
                self.generate_value_expr(output, argument)?;
                output.push(')');
            }
            Value::Lambda(_, param, body) => {
                output.push_str("fn(");
                self.generate_pattern(output, param)?;
                output.push_str(") { ");
                self.generate_value_expr(output, body)?;
                output.push_str(" }");
            }
            Value::LetDefinition(_, name, def, body) => {
                if !def.input_types.is_empty() {
                    return Err(unsupported("LetDefinition with function parameters"));
                }
                // Gleam uses: let name = value \n body (no 'in' keyword)
                output.push_str("{ let ");
                output.push_str(&name.to_snake_case());
                output.push_str(" = ");
                self.generate_value_expr(output, def.body.get_expression()?)?;
                output.push_str("\n  ");
                self.generate_value_expr(output, body)?;
                output.push_str(" }");
            }
            Value::Destructure(_, pattern, value, body) => {
                output.push_str("{ let ");
                if !irrefutable(pattern) {
                    output.push_str("assert ");
                }
                self.generate_pattern(output, pattern)?;
                output.push_str(" = ");
                self.generate_value_expr(output, value)?;
                output.push_str("\n  ");
                self.generate_value_expr(output, body)?;
                output.push_str(" }");
            }
            Value::IfThenElse(_, condition, then_branch, else_branch) => {
                // Gleam supports case for boolean pattern matching
                output.push_str("case ");
                self.generate_value_expr(output, condition)?;
                output.push_str(" { True -> ");
                self.generate_value_expr(output, then_branch)?;
                output.push_str(" False -> ");
                self.generate_value_expr(output, else_branch)?;
                output.push_str(" }");
            }
            Value::Record(..) => {
                return Err(unsupported(
                    "Record expression requires a resolved named Gleam constructor",
                ));
            }
            Value::Field(_, record, field) => {
                self.generate_value_expr(output, record)?;
                output.push('.');
                output.push_str(&field.to_snake_case());
            }
            Value::Tuple(_, elements) => {
                output.push_str("#(");
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    self.generate_value_expr(output, elem)?;
                }
                output.push(')');
            }
            Value::PatternMatch(_, subject, cases) => {
                output.push_str("case ");
                self.generate_value_expr(output, subject)?;
                output.push_str(" { ");
                for (i, case) in cases.iter().enumerate() {
                    if i > 0 {
                        output.push(' ');
                    }
                    self.generate_pattern(output, &case.0)?;
                    output.push_str(" -> ");
                    self.generate_value_expr(output, &case.1)?;
                }
                output.push_str(" }");
            }
            Value::Constructor(_, fqname) => {
                output.push_str(&fqname.local_name.to_title_case());
            }
            Value::Reference(_, fqname) => {
                // For references, output just the local name for now
                output.push_str(&fqname.local_name.to_snake_case());
            }
            Value::List(_, items) => {
                output.push('[');
                for (i, item) in items.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    self.generate_value_expr(output, item)?;
                }
                output.push(']');
            }
            Value::Unit(_) => {
                output.push_str("Nil");
            }
            Value::FieldFunction(..) => return Err(unsupported("FieldFunction")),
            Value::LetRecursion(..) => return Err(unsupported("LetRecursion")),
            Value::UpdateRecord(..) => return Err(unsupported("UpdateRecord")),
            Value::Hole(..) => return Err(unsupported("Hole")),
        }
        Ok(())
    }

    /// Generate pattern
    fn generate_pattern(&self, output: &mut String, pattern: &MorphirPattern) -> Result<()> {
        match pattern {
            MorphirPattern::WildcardPattern(_) => {
                output.push('_');
            }
            MorphirPattern::AsPattern(_, sub_pattern, name) => {
                // In Gleam, `x as name` is often just a binding
                // If sub_pattern is wildcard, just output the name
                if matches!(**sub_pattern, MorphirPattern::WildcardPattern(_)) {
                    output.push_str(&name.to_snake_case());
                } else {
                    self.generate_pattern(output, sub_pattern)?;
                    output.push_str(" as ");
                    output.push_str(&name.to_snake_case());
                }
            }
            MorphirPattern::TuplePattern(_, elements) => {
                output.push_str("#(");
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    self.generate_pattern(output, elem)?;
                }
                output.push(')');
            }
            MorphirPattern::ConstructorPattern(_, fqname, args) => {
                output.push_str(&fqname.local_name.to_title_case());
                if !args.is_empty() {
                    output.push('(');
                    for (i, arg) in args.iter().enumerate() {
                        if i > 0 {
                            output.push_str(", ");
                        }
                        self.generate_pattern(output, arg)?;
                    }
                    output.push(')');
                }
            }
            MorphirPattern::LiteralPattern(_, lit) => {
                self.generate_literal(output, lit)?;
            }
            MorphirPattern::UnitPattern(_) => {
                output.push_str("Nil");
            }
            MorphirPattern::HeadTailPattern(_, head, tail) => {
                output.push('[');
                self.generate_pattern(output, head)?;
                let mut rest = tail.as_ref();
                while let MorphirPattern::HeadTailPattern(_, head, tail) = rest {
                    output.push_str(", ");
                    self.generate_pattern(output, head)?;
                    rest = tail;
                }
                match rest {
                    MorphirPattern::EmptyListPattern(_) => {}
                    MorphirPattern::WildcardPattern(_) => output.push_str(", .._"),
                    MorphirPattern::AsPattern(_, pattern, name)
                        if matches!(pattern.as_ref(), MorphirPattern::WildcardPattern(_)) =>
                    {
                        output.push_str(", ..");
                        output.push_str(&name.to_snake_case());
                    }
                    _ => {
                        return Err(unsupported(
                            "list tail pattern requires a binding, wildcard, or list pattern",
                        ));
                    }
                }
                output.push(']');
            }
            MorphirPattern::EmptyListPattern(_) => {
                output.push_str("[]");
            }
        }
        Ok(())
    }

    /// Generate literal
    fn generate_literal(&self, output: &mut String, lit: &MorphirLiteral) -> Result<()> {
        super::literals::generate(output, lit)
    }
}

fn unsupported(feature: &str) -> std::io::Error {
    std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        format!("Gleam generation does not support {feature}"),
    )
}

fn irrefutable(pattern: &MorphirPattern) -> bool {
    match pattern {
        MorphirPattern::WildcardPattern(_) | MorphirPattern::UnitPattern(_) => true,
        MorphirPattern::AsPattern(_, pattern, _) => irrefutable(pattern),
        MorphirPattern::TuplePattern(_, elements) => elements.iter().all(irrefutable),
        MorphirPattern::ConstructorPattern(..)
        | MorphirPattern::LiteralPattern(..)
        | MorphirPattern::HeadTailPattern(..)
        | MorphirPattern::EmptyListPattern(_) => false,
    }
}

/// Helper trait for ValueBody to extract the expression
trait ValueBodyExt {
    fn get_expression(&self) -> Result<&Value>;
}

impl ValueBodyExt for morphir_core::ir::v4::ValueBody {
    fn get_expression(&self) -> Result<&Value> {
        match self {
            morphir_core::ir::v4::ValueBody::Expression(body) => Ok(body),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Expected expression body",
            )),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vfs::MemoryVfs;
    use indexmap::IndexMap;
    use morphir_core::ir::v4::Access as MorphirAccess;
    use morphir_core::ir::v4::{AccessControlled, ModuleDefinition};
    use morphir_core::naming::ModuleName;
    use std::path::PathBuf;

    #[test]
    fn test_generate_module() {
        let vfs = MemoryVfs::new();
        let output_dir = PathBuf::from("/test");
        let package_name = "test-package".to_string();
        let visitor = MorphirToGleamVisitor::new(vfs, output_dir, package_name);

        let module_name = ModuleName::parse("test_module");
        let module_def = AccessControlled {
            access: MorphirAccess::Public,
            value: ModuleDefinition {
                types: IndexMap::new(),
                values: IndexMap::new(),
                doc: None,
            },
        };

        // Test that visitor can generate module
        let result = visitor.visit_module(&module_name, &module_def);
        assert!(result.is_ok());
    }

    #[test]
    fn test_generate_literal() {
        let vfs = MemoryVfs::new();
        let visitor = MorphirToGleamVisitor::new(vfs, PathBuf::from("/test"), "test".to_string());

        let mut output = String::new();
        let lit = MorphirLiteral::Bool(true);
        visitor.generate_literal(&mut output, &lit).unwrap();
        assert_eq!(output, "True");

        output.clear();
        let lit = MorphirLiteral::Integer(42.into());
        visitor.generate_literal(&mut output, &lit).unwrap();
        assert_eq!(output, "42");

        output.clear();
        let lit = MorphirLiteral::String("hello".to_string());
        visitor.generate_literal(&mut output, &lit).unwrap();
        assert_eq!(output, "\"hello\"");
    }
}
