// Generated by Morphir Gleam Backend

pub fn run() {
  #({ let #(left, right) = #(1, 2)
  left }, [1, ..[2, 3]], case True { True -> { let #(left, right) = #(1, 2)
  left } False -> 0 }, [{ let #(left, right) = #(1, 2)
  left }], [{ let #(left, right) = #(1, 2)
  left }, ..[]], case Nil { Nil -> { let #(left, right) = #(1, 2)
  left } })
}

