use std::fs;

use chrono::NaiveDate;
use morphir_okf::model::Bundle;

use crate::error::Result;

use super::MARKER;
use super::edit::{line_terminator, with_terminator};
use super::model::{Intent, IntentState, intents};

// ----------------------------------------------------------- index generation

/// Rewrites the intent bundle's index below the marker, grouped by state.
/// Returns whether anything changed.
///
/// Generated rather than hand-maintained, which is what stops it rotting —
/// and it is the human-readable answer to "what is pending, in flight, and no
/// longer valid".
pub fn generate_index(b: &Bundle, today: NaiveDate) -> Result<bool> {
    let text = fs::read_to_string(&b.index.file)?;
    let eol = line_terminator(&text);
    let normalized = text.replace("\r\n", "\n");
    let preamble = match normalized.find(MARKER) {
        Some(at) => normalized[..at + MARKER.len()].to_string(),
        None => format!("{}\n\n{MARKER}", normalized.trim_end()),
    };
    let generated = render_sections(&intents(b), today);
    let updated = format!("{preamble}\n\n{generated}");
    if updated == normalized {
        Ok(false)
    } else {
        // Same reasoning as `set_keys`: the preamble above the marker is the
        // author's, and regenerating below it must not reflow their lines.
        fs::write(&b.index.file, with_terminator(&updated, eol))?;
        Ok(true)
    }
}

fn render_sections(items: &[Intent<'_>], today: NaiveDate) -> String {
    let mut sb = String::new();
    sb.push_str(&format!(
        "_Generated by `kb refresh` — do not edit below the marker. Last built {today}._\n"
    ));
    for st in IntentState::DISPLAY_ORDER {
        let mut group: Vec<&Intent<'_>> = items.iter().filter(|i| i.state() == Some(st)).collect();
        group.sort_by_key(|i| i.id());
        if !group.is_empty() {
            sb.push_str(&format!("\n## {} ({})\n\n", heading(st), group.len()));
            // Flags live in the link text, never after the description: the
            // bullet's trailing text must stay verbatim equal to the
            // concept's `description`, which is what `kb check` enforces.
            for i in group {
                sb.push_str(&bullet(i));
            }
        }
    }
    let stateless: Vec<&Intent<'_>> = items.iter().filter(|i| i.state().is_none()).collect();
    if !stateless.is_empty() {
        sb.push_str(&format!("\n## Without a state ({})\n\n", stateless.len()));
        for i in stateless {
            sb.push_str(&bullet(i));
        }
    }
    if items.is_empty() {
        sb.push_str(
            "\nNo intent recorded yet. `kb intent new --title … --description … --kind feature`\n",
        );
    }
    sb
}

fn bullet(i: &Intent<'_>) -> String {
    format!(
        "* [{}]({}) - {}\n",
        link_text(i),
        i.doc.bundle_path(),
        i.description().unwrap_or_default().trim()
    )
}

fn link_text(i: &Intent<'_>) -> String {
    let mut flags: Vec<&str> = Vec::new();
    if i.breaking() {
        flags.push("breaking");
    }
    if let Some(k) = i.kind() {
        flags.push(k.label());
    }
    if flags.is_empty() {
        format!("{} {}", i.id(), i.title())
    } else {
        format!("{} {} — {}", i.id(), i.title(), flags.join(", "))
    }
}

fn heading(st: IntentState) -> &'static str {
    match st {
        IntentState::InProgress => "In progress",
        IntentState::Backlog => "Backlog",
        IntentState::Refinement => "In refinement",
        IntentState::Released => "Released",
        IntentState::Cancelled => "Cancelled",
        IntentState::Superseded => "Superseded",
    }
}
