# @generated by usage-cli from docs/morphir.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in morphir." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_morphir 'name morphir
bin morphir
version "0.1.0"
about "CLI for working with Morphir IR - functional domain modeling and business logic"
usage "Usage: morphir [OPTIONS] [COMMAND]"
flag "-h --help" help="Print help (use --help-all to include experimental commands)"
flag --help-all help="Print help including experimental commands"
flag "-V --version" help="Print version"
flag "-h --help" help="Print help (use --help-all to include experimental commands)"
flag --help-all help="Print help including experimental commands"
flag "-V --version" help="Print version"
cmd validate hide=#true help="[Experimental] Validate Morphir IR models" {
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
}
cmd generate hide=#true help="[Experimental] Generate code from Morphir IR" {
    flag "-t --target" help="Target language or format" {
        arg <TARGET>
    }
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
    flag "-o --output" help="Output directory" {
        arg <OUTPUT>
    }
}
cmd transform hide=#true help="[Experimental] Transform Morphir IR" {
    flag "-i --input" help="Path to the Morphir IR file or directory" {
        arg <INPUT>
    }
    flag "-o --output" help="Output path" {
        arg <OUTPUT>
    }
}
cmd tool subcommand_required=#true help="Manage Morphir tools, distributions, and extensions" {
    cmd install help="Install a Morphir tool or extension" {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the tool to install"
    }
    cmd list help="List installed Morphir tools"
    cmd update help="Update an installed Morphir tool" {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the tool to update"
    }
    cmd uninstall help="Uninstall a Morphir tool" {
        arg <NAME> help="Name of the tool to uninstall"
    }
}
cmd dist subcommand_required=#true help="Manage Morphir distributions" {
    cmd install help="Install a Morphir distribution" {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the distribution to install"
    }
    cmd list help="List installed Morphir distributions"
    cmd update help="Update an installed Morphir distribution" {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the distribution to update"
    }
    cmd uninstall help="Uninstall a Morphir distribution" {
        arg <NAME> help="Name of the distribution to uninstall"
    }
}
cmd extension subcommand_required=#true help="Manage Morphir extensions" {
    cmd install help="Install a Morphir extension" {
        flag "-v --version" help="Version to install (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the extension to install"
    }
    cmd list help="List installed Morphir extensions"
    cmd update help="Update an installed Morphir extension" {
        flag "-v --version" help="Version to update to (defaults to latest)" {
            arg <VERSION>
        }
        arg <NAME> help="Name of the extension to update"
    }
    cmd uninstall help="Uninstall a Morphir extension" {
        arg <NAME> help="Name of the extension to uninstall"
    }
}
cmd ir subcommand_required=#true help="Manage Morphir IR" {
    cmd migrate help="Migrate IR between versions" {
        flag "-i --input" help="Input file, directory, or remote source (e.g., github:owner/repo)" required=#true {
            arg <INPUT>
        }
        flag "-o --output" help="Output file or directory" required=#true {
            arg <OUTPUT>
        }
        flag --target-version help="Target version (v4 or classic)" {
            arg <TARGET_VERSION>
        }
        flag --force-refresh help="Force refresh cached remote sources"
        flag --no-cache help="Skip cache entirely for remote sources"
    }
}
cmd schema help="Generate JSON Schema for Morphir IR" {
    flag "-o --output" help="Output file path (optional)" {
        arg <OUTPUT>
    }
}
cmd usage hide=#true help="Output usage spec for documentation generation"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_morphir.spec"
echo $_usage_spec_morphir > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
