# @generated by usage-cli from docs/morphir.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in morphir." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_morphir 'name morphir.usage.kdl
bin morphir.usage.kdl
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_morphir.spec"
echo $_usage_spec_morphir > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc morphir -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
