source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-redirect-from" # Keeps renamed pages reachable at their old URLs
gem "webrick" # Required for Ruby 3+

# just-the-docs theme dependencies
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
gem "rake"
