use std::collections::BTreeMap;
use std::fs;

use chrono::NaiveDate;

use crate::error::Result;

use super::model::{LockEntry, SyncBundle, SyncKind, SyncLock};

/// The generated region in a sync bundle's index.
pub const INDEX_MARKER: &str = "<!-- kb:sources -->";
/// Rewrites the bundle index below the marker, grouped by the mirror's top-level
/// directories. Generated because forty hand-written bullets rot on the first
/// `pull`. Returns whether the file changed.
pub fn generate_index(sb: &SyncBundle, lock: &SyncLock, today: NaiveDate) -> Result<bool> {
    let file = &sb.bundle.index.file;
    let text = fs::read_to_string(file)?;
    let normalized = text.replace("\r\n", "\n");
    let preamble = match normalized.find(INDEX_MARKER) {
        Some(at) => normalized[..at + INDEX_MARKER.len()].to_string(),
        None => format!("{}\n\n{INDEX_MARKER}", normalized.trim_end()),
    };
    let updated = format!("{preamble}\n\n{}", render_index_body(sb, lock, today));
    if updated == normalized {
        Ok(false)
    } else {
        fs::write(file, updated)?;
        Ok(true)
    }
}

fn render_index_body(sb: &SyncBundle, lock: &SyncLock, today: NaiveDate) -> String {
    let mut sbuf = String::new();
    // The lockfile's date, not today's: this region has to be stable across a pull
    // that imports nothing, or the index churns on every run exactly as the
    // lockfile used to.
    let built = if lock.imported_at.is_empty() {
        today.to_string()
    } else {
        lock.imported_at.clone()
    };
    sbuf.push_str(&format!(
        "_Generated by `kb sync pull` — do not edit below the marker. Last built {built}"
    ));
    if !lock.base_commit.is_empty() {
        let short: String = lock.base_commit.chars().take(8).collect();
        sbuf.push_str(&format!(", from {}@{short}", sb.manifest.repo));
    }
    sbuf.push_str("._\n");
    let mut concepts: Vec<&LockEntry> = lock
        .files
        .iter()
        .filter(|e| e.kind == SyncKind::Concept)
        .collect();
    concepts.sort_by(|a, b| a.path.cmp(&b.path));
    let mut assets: Vec<&LockEntry> = lock
        .files
        .iter()
        .filter(|e| e.kind == SyncKind::Asset)
        .collect();
    assets.sort_by(|a, b| a.path.cmp(&b.path));
    let mut groups: BTreeMap<String, Vec<&LockEntry>> = BTreeMap::new();
    for e in concepts {
        let group = e.path.split('/').take(3).collect::<Vec<_>>().join("/");
        groups.entry(group).or_default().push(e);
    }
    for (group, items) in groups {
        sbuf.push_str(&format!("\n## {group}\n\n"));
        for e in items {
            let link = format!("/{}/{}", sb.manifest.root, e.path);
            // The bullet text must equal the concept's own `description` verbatim —
            // that equality is what `index-description-drift` enforces, and
            // generating the text from anything else would break it on import.
            let doc = sb.bundle.concept_at(&link);
            let title = doc
                .map(|d| d.display_title())
                .unwrap_or_else(|| e.path.rsplit('/').next().unwrap_or(&e.path).to_string());
            let description = doc
                .and_then(|d| d.fm().description())
                .map(|d| d.trim().to_string())
                .unwrap_or_else(|| {
                    format!("Upstream source document {}:{}.", sb.manifest.repo, e.path)
                });
            sbuf.push_str(&format!("* [{title}]({link}) - {description}\n"));
        }
    }
    if !assets.is_empty() {
        sbuf.push_str(&format!("\n## Assets ({})\n\n", assets.len()));
        sbuf.push_str(
            "Mirrored byte-for-byte and not concept documents — schemas, fixtures, examples, sidebar metadata.\n\n",
        );
        for e in &assets {
            sbuf.push_str(&format!("* `{}/{}`\n", sb.manifest.root, e.path));
        }
    }
    sbuf
}
